### ISSUE TITLE
HW 3 Problem 3

### ISSUE THREAD

**Issue by baowenxuan** [LFhase/Learning_CS224w#3]
Hi, I think there are some problems inthe implementation of 3.1. The `curr_alternativing_vote` variable should be flipped every time you use it (to assign a node), rather than being flipped at each iteration (or `day` in your code). After fixing that, the answer will be:
```
Q1:
In graph 1, candidate B wins by 96 votes
In graph 2, candidate B wins by 256 votes
```
which could pass the sanity check. 
See: https://github.com/LFhase/Learning_CS224w/blob/2d124b51d5044a41423dade4e15db476c16ed69c/Homework/HW3/hw3-q3-starter.py#L99

**Comment by LFhase** [comment]
Yes, you are right 😀. Thanks for pointing out this error. I've updated the solution [2d124b5](https://github.com/LFhase/Learning_CS224w/commit/2d124b51d5044a41423dade4e15db476c16ed69c).

**Comment by LFhase** [comment]
Let me close the issue if there's no further question. Feel free to open it if not.
